// Package pricing is the order calculator, ported from the front end.
//
// The captured page computes every price in the browser, inside a closed IIFE
// (docs/02-business-rules.md, BR-3 through BR-6). This package is that same
// arithmetic in Go, with the thresholds lifted out into Rules so they can be
// configured instead of edited.
//
// It is a PORT, not a reimplementation. Where the JavaScript does something
// surprising, this does the same surprising thing, and says why in a comment.
// The two are held together by a differential test: testdata/tier_cases.json is
// generated by running the real analyze() out of the mirror over hundreds of
// date sets, and TestMatchesShippedEngine asserts this package agrees on every
// one. If they ever diverge, that test fails rather than a customer being
// quoted one number and charged another.
//
// No I/O. Money is int64 whole rupiah and every operation is integer.
package pricing

import (
	"errors"
	"fmt"
)

// Rules are the thresholds the tier classifier compares against. They live in
// the pricing_rules table; Default() reproduces the captured page exactly.
type Rules struct {
	WeeklyMinDays                 int `json:"weekly_min_days"`
	MonthlyMinDays                int `json:"monthly_min_days"`
	ConsecutiveFlexiWeeklyMaxDays int `json:"consecutive_flexi_weekly_max_days"`
	FlexiMonthlyMaxSpanDays       int `json:"flexi_monthly_max_span_days"`
	WeekdayRoutineMaxSpanDays     int `json:"weekday_routine_max_span_days"`
	WeeklyRoutineMaxSpanDays      int `json:"weekly_routine_max_span_days"`
	WeeklyRoutineMinDaysInWeek    int `json:"weekly_routine_min_days_in_week"`
	PaxTableMaxPax                int `json:"pax_table_max_pax"`
}

// Default returns the rules as the captured page hard-codes them.
func Default() Rules {
	return Rules{
		WeeklyMinDays:                 5,
		MonthlyMinDays:                20,
		ConsecutiveFlexiWeeklyMaxDays: 14,
		FlexiMonthlyMaxSpanDays:       45,
		WeekdayRoutineMaxSpanDays:     31,
		WeeklyRoutineMaxSpanDays:      14,
		WeeklyRoutineMinDaysInWeek:    5,
		PaxTableMaxPax:                5,
	}
}

var (
	ErrWeeklyMin    = errors.New("pricing: weekly_min_days must be at least 1")
	ErrMonthlyOrder = errors.New("pricing: monthly_min_days must be greater than weekly_min_days")
	ErrFlexiCeiling = errors.New("pricing: consecutive_flexi_weekly_max_days must sit between weekly_min_days and monthly_min_days")
	ErrFlexiSpan    = errors.New("pricing: flexi_monthly_max_span_days must be at least monthly_min_days")
	ErrWeekdaySpan  = errors.New("pricing: weekday_routine_max_span_days must be at least monthly_min_days")
	ErrWeeklySpan   = errors.New("pricing: weekly_routine_max_span_days must be at least weekly_min_days")
	ErrWeekCount    = errors.New("pricing: weekly_routine_min_days_in_week must be between 1 and 7")
	ErrPaxTable     = errors.New("pricing: pax_table_max_pax must be at least 1")
)

// Validate rejects rule sets that would make a branch of the classifier
// unreachable. Every one of these is a silent failure if it gets through: the
// prices still compute, they are just computed by the wrong branch.
func (r Rules) Validate() error {
	switch {
	case r.WeeklyMinDays < 1:
		return fmt.Errorf("%w (got %d)", ErrWeeklyMin, r.WeeklyMinDays)
	case r.MonthlyMinDays <= r.WeeklyMinDays:
		return fmt.Errorf("%w (weekly=%d monthly=%d)", ErrMonthlyOrder, r.WeeklyMinDays, r.MonthlyMinDays)
	case r.ConsecutiveFlexiWeeklyMaxDays < r.WeeklyMinDays ||
		r.ConsecutiveFlexiWeeklyMaxDays >= r.MonthlyMinDays:
		return fmt.Errorf("%w (got %d, weekly=%d monthly=%d)", ErrFlexiCeiling,
			r.ConsecutiveFlexiWeeklyMaxDays, r.WeeklyMinDays, r.MonthlyMinDays)
	case r.FlexiMonthlyMaxSpanDays < r.MonthlyMinDays:
		return fmt.Errorf("%w (got %d, monthly=%d)", ErrFlexiSpan, r.FlexiMonthlyMaxSpanDays, r.MonthlyMinDays)
	case r.WeekdayRoutineMaxSpanDays < r.MonthlyMinDays:
		return fmt.Errorf("%w (got %d, monthly=%d)", ErrWeekdaySpan, r.WeekdayRoutineMaxSpanDays, r.MonthlyMinDays)
	case r.WeeklyRoutineMaxSpanDays < r.WeeklyMinDays:
		return fmt.Errorf("%w (got %d, weekly=%d)", ErrWeeklySpan, r.WeeklyRoutineMaxSpanDays, r.WeeklyMinDays)
	case r.WeeklyRoutineMinDaysInWeek < 1 || r.WeeklyRoutineMinDaysInWeek > 7:
		return fmt.Errorf("%w (got %d)", ErrWeekCount, r.WeeklyRoutineMinDaysInWeek)
	case r.PaxTableMaxPax < 1:
		return fmt.Errorf("%w (got %d)", ErrPaxTable, r.PaxTableMaxPax)
	}
	return nil
}
